# Generated by Django 4.2.7 on 2023-11-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(max_length=255),
        ),
    ]
